source "https://rubygems.org"

gem 'rake'
gem 'foodcritic', '7.1.0'
gem 'chef'
gem 'rack', '1.6.5'
gem 'chefspec',   '5.3.0'
gem 'colorize',   '0.6.0'
gem 'fauxhai', '3.9.0'
gem 'test-unit'
gem 'rspec-rails'
gem 'factory_girl_rails'
gem 'ffaker'
gem 'capybara'
gem 'database_cleaner'
gem 'launchy'
gem 'ffi', '<1.9.3'
gem 'rails_helper'
gem 'chef-sugar'
gem 'chef-handler-datadog'
